# *Data Loading*

In [16]:
import pandas as pd
import requests
from datetime import timedelta

df = pd.read_csv("../data/dataset_with_holidays.csv")
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delayed,...,order_day,is_weekend,order_date,expected_date,transit_holidays,holiday_count_transit,holiday_names_transit,weekend_count_transit,holiday_or_weekend_transit_flag,holiday_proximity_feature
0,250.99,amazon logistics,automobile parts,ev bike,standard,west,clear,235.6,48.07,no,...,0,0,2024-10-21,2024-10-23,[],0,NaN,0,0,1
1,250.99,amazon logistics,clothing,bike,express,central,stormy,81.8,45.51,yes,...,1,0,2024-01-02,2024-01-02,[],0,NaN,0,0,1
2,250.99,amazon logistics,clothing,van,same day,north,clear,282.9,31.33,yes,...,4,0,2024-05-31,2024-06-01,[],0,NaN,1,1,8
3,250.99,amazon logistics,cosmetics,ev bike,two day,central,hot,88.6,8.67,no,...,2,0,2024-01-03,2024-01-05,[],0,NaN,0,0,2
4,250.99,amazon logistics,cosmetics,ev van,two day,east,rainy,204.2,8.09,no,...,1,0,2024-03-19,2024-03-21,['March Equinox'],1,March Equinox,0,1,1

In [17]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 36 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   delivery_id                      25000 non-null  float64
 1   delivery_partner                 25000 non-null  object
 2   package_type                     25000 non-null  object
 3   vehicle_type                     25000 non-null  object
 4   delivery_mode                    25000 non-null  object
 5   region                           25000 non-null  object
 6   weather_condition                25000 non-null  object
 7   distance_km                      25000 non-null  float64
 8   package_weight_kg                25000 non-null  float64
 9   delayed                          25000 non-null  object
 10  delivery_status                  25000 non-null  object
 11  delivery_rating                  25000 non-null  int64
 12  delivery_cost                    25000 non-null  float64
 13  expected_time_hours_recon        25000 non-null  float64
 14  speed_kmph_recon                 25000 non-null  int64
 15  weather_mult_recon               25000 non-null  float64
 16  delivery_time_hours_recon        25000 non-null  float64
 17  partner_mult_recon               25000 non-null  float64
 18  delay_hours_recon                25000 non-null  float64
 19  delayed_flag_recon               25000 non-null  int64
 20  order_date_recon                 25000 non-null  object
 21  order_ts_recon                   25000 non-null  object
 22  delivery_ts_recon                25000 non-null  object
 23  expected_ts_recon                25000 non-null  object
 24  hour                             25000 non-null  int64
 25  order_hour                       25000 non-null  int64
 26  order_day                        25000 non-null  int64
 27  is_weekend                       25000 non-null  int64
 28  order_date                       25000 non-null  object
 29  expected_date                    25000 non-null  object
 30  transit_holidays                 25000 non-null  object
 31  holiday_count_transit            25000 non-null  int64
 32  holiday_names_transit            8296 non-null   object
 33  weekend_count_transit            25000 non-null  int64
 34  holiday_or_weekend_transit_flag  25000 non-null  int64
 35  holiday_proximity_feature        25000 non-null  int64
dtypes: float64(9), int64(11), object(16)
memory usage: 6.9+ MB

,delivery_id,distance_km,package_weight_kg,delivery_rating,delivery_cost,expected_time_hours_recon,speed_kmph_recon,weather_mult_recon,delivery_time_hours_recon,partner_mult_recon,delay_hours_recon,delayed_flag_recon,hour,order_hour,order_day,is_weekend,holiday_count_transit,weekend_count_transit,holiday_or_weekend_transit_flag,holiday_proximity_feature
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.0000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,150.390436,25.145898,3.666000,864.944579,33.053344,39.9762,1.100310,5.360406,0.999994,-27.692938,0.029400,12.515400,12.515400,2.987960,0.282400,0.393200,0.641800,0.621280,2.648600
std,7212.732314,86.409745,14.368663,1.149964,435.712593,17.592341,6.4653,0.064465,2.631007,0.003666,17.636803,0.168928,2.751564,2.751564,1.996551,0.450176,0.611006,0.767383,0.485078,2.627142
min,250.990000,3.600000,0.670000,1.000000,95.667400,8.000000,30.0000,1.000000,0.640518,0.993437,-48.086207,0.000000,8.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6250.750000,75.900000,12.680000,3.000000,490.800000,24.000000,35.0000,1.050000,3.180450,0.998812,-44.388864,0.000000,10.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,12500.500000,151.000000,25.145000,4.000000,867.535000,26.400000,40.0000,1.100000,5.227587,1.000945,-23.192956,0.000000,12.000000,12.000000,3.000000,0.000000,0.000000,0.000000,1.000000,2.000000
75%,18750.250000,224.900000,37.660000,5.000000,1237.910000,48.000000,45.0000,1.150000,7.307020,1.002187,-14.075366,0.000000,15.000000,15.000000,5.000000,1.000000,1.000000,1.000000,1.000000,4.000000
max,24750.010000,297.100000,49.520000,5.000000,1632.720600,52.800000,50.0000,1.200000,13.682192,1.005584,4.860295,1.000000,18.000000,18.000000,6.000000,1.000000,3.000000,2.000000,1.000000,13.000000

In [18]:
df.isnull().sum()

delivery_id                            0
delivery_partner                       0
package_type                           0
vehicle_type                           0
delivery_mode                          0
region                                 0
weather_condition                      0
distance_km                            0
package_weight_kg                      0
delayed                                0
delivery_status                        0
delivery_rating                        0
delivery_cost                          0
expected_time_hours_recon              0
speed_kmph_recon                       0
weather_mult_recon                     0
delivery_time_hours_recon              0
partner_mult_recon                     0
delay_hours_recon                      0
delayed_flag_recon                     0
order_date_recon                       0
order_ts_recon                         0
delivery_ts_recon                      0
expected_ts_recon                      0
hour                                   0
order_hour                             0
order_day                              0
is_weekend                             0
order_date                             0
expected_date                          0
transit_holidays                       0
holiday_count_transit                  0
holiday_names_transit              16704
weekend_count_transit                  0
holiday_or_weekend_transit_flag        0
holiday_proximity_feature              0
dtype: int64

In [19]:
df["order_ts_recon"] = pd.to_datetime(df["order_ts_recon"])
df["expected_ts_recon"] = pd.to_datetime(df["expected_ts_recon"])

df["order_date"] = df["order_ts_recon"].dt.date
df["expected_date"] = df["expected_ts_recon"].dt.date

In [20]:
all_dates = set()

for i in range(len(df)):

    start = df.loc[i, "order_date"]
    end = df.loc[i, "expected_date"]

    current = start

    while current <= end:
        all_dates.add(current)
        current += timedelta(days=1)

all_dates = sorted(all_dates)

print("Unique transit dates:", len(all_dates))

Unique transit dates: 365

# *Weather enrichment*

In [26]:
import numpy as np

np.random.seed(42)

# Generate synthetic weather features
df["temperature"] = np.random.normal(30, 5, len(df))
df["humidity"] = np.random.uniform(50, 95, len(df))
df["wind_speed"] = np.random.uniform(0, 20, len(df))
df["precipitation"] = np.random.exponential(2, len(df))

# Weather condition
conditions = ["clear", "cloudy", "rainy", "stormy", "foggy"]
df["weather_condition"] = np.random.choice(
    conditions,
    len(df),
    p=[0.45, 0.25, 0.2, 0.05, 0.05]
)

# Convert to lowercase to avoid mismatch
df["weather_condition"] = df["weather_condition"].str.lower()

# Bad weather flag
bad_conditions = ["rainy", "stormy", "foggy"]

df["bad_weather_flag_api"] = (
    df["weather_condition"].isin(bad_conditions)
).astype(int)

In [27]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delayed,...,holiday_or_weekend_transit_flag,holiday_proximity_feature,api_temperature,api_humidity,api_wind_speed,precipitation,bad_weather_flag_api,temperature,humidity,wind_speed
0,250.99,amazon logistics,automobile parts,ev bike,standard,west,clear,235.6,48.07,no,...,0,1,32.483571,74.097849,17.056317,3.506765,0,32.483571,74.097849,17.056317
1,250.99,amazon logistics,clothing,bike,express,central,clear,81.8,45.51,yes,...,0,1,29.308678,94.778295,15.486040,2.943648,0,29.308678,94.778295,15.486040
2,250.99,amazon logistics,clothing,van,same day,north,clear,282.9,31.33,yes,...,1,8,33.238443,56.395895,13.558508,1.892765,0,33.238443,56.395895,13.558508
3,250.99,amazon logistics,cosmetics,ev bike,two day,central,stormy,88.6,8.67,no,...,0,2,37.615149,88.800189,7.938182,2.332062,1,37.615149,88.800189,7.938182
4,250.99,amazon logistics,cosmetics,ev van,two day,east,foggy,204.2,8.09,no,...,1,1,28.829233,72.374135,2.726783,1.645159,1,28.829233,72.374135,2.726783

In [29]:
df.to_csv("../Data/dataset_with_weather_feature.csv", index=False)